site_name: SHARP-on-MCP
extra_javascript:
  - javascript/readthedocs.js
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview: index.md
  - The Problem We're Solving: problem.md
  - Scope and Components: sharp-on-mcp.md
  - Specification:
      - Terminology: terminology.md
      - 3 Key Components: key-components.md
  - Contributing:
      - Getting Started: getting-started.md
      - Contributing and Bounty Program: ask-collaborators.md
